global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'customer-command-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-command-processor:8080']
  - job_name: 'customer-query-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-query-processor:8081']