------------------------------------------------[RESTAURANT]---------------------------------------------------------

CREATE TABLE restaurant
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(256)                            NOT NULL,
    max_capacity       INTEGER                                 NOT NULL,
    working_start_time time WITHOUT TIME ZONE                  NOT NULL,
    working_end_time   time WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_restaurant PRIMARY KEY (id)
);

------------------------------------------------[BOOKING]---------------------------------------------------------

CREATE TABLE booking_event_store
(
    id                 UUID                        NOT NULL,
    customer_uid       UUID,
    aggregate_uid      UUID                        NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    version            INTEGER                     NOT NULL,
    type               VARCHAR(255)                NOT NULL,
    place_capacity     INTEGER,
    restaurant_id      BIGINT,
    booking_start_time TIMESTAMP WITHOUT TIME ZONE,
    booking_end_time   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_booking_event_store PRIMARY KEY (id)
);

ALTER TABLE booking_event_store
    ADD CONSTRAINT FK_BOOKING_EVENT_STORE_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);